### ISSUE TITLE
Adding a source works, but produces error message

### ISSUE THREAD

**Issue by bgschiller** [nathanielksmith/prosaic#36]
I'm trying to add the [transcript of mean_girls](http://162.209.109.174/mean_girls.txt), with `prosaic source new mean_girls mean_girls.txt`. The command prints an error message, but exits successfully:

![](http://162.209.109.174/2016-12-09_20-55-53CVWFFS.png)

It seems to have added the source to my db though:

![](http://162.209.109.174/2016-12-09_20-56-4643T40H.png)
![](http://162.209.109.174/2016-12-09_20-58-09UKOS61.png)

I'd be happy to try and fix this myself, but do you have any advice? Perhaps the error is thrown part-way through processing the file, so most of the phrases have already been added?

Thanks!

**Comment by nathanielksmith** [comment]
ah, thanks for reporting!

this was a really stupid bug I made with error handling -- there wasn't actually an error, the number is actually the source id (i was misinterpreting the return of `process_text` as an error.

This is fixed in 6.1.1!
