### ISSUE TITLE
prosaic requires NTLK punkt tokenizer

### ISSUE THREAD

**Issue by audiodude** [nathanielksmith/prosaic#6]
When I run the commands in the README, specifically: `hy __init__.hy load some_text0.txt some_mongo_db_name`

I get
```
LookupError:
**********************************************************************
  Resource 'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
```

**Comment by nathanielksmith** [comment]
Hm. I think this is fixed? I just did a clean install of this to a brand new computer and didn't have any issues with NLTK finding its stuff. Perhaps I wasn't formerly including nltk_data as package data?
